name: TesteWorkFlow
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Ambiente-teste
    steps:
      - name: Run a one-line script
        run: echo Hello, World
